# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\PtychoControl\pcUI.ui'
#
# Created: Fri Apr 10 14:42:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pcMainWindow(object):
    def setupUi(self, pcMainWindow):
        pcMainWindow.setObjectName(_fromUtf8("pcMainWindow"))
        pcMainWindow.resize(775, 653)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pcMainWindow.sizePolicy().hasHeightForWidth())
        pcMainWindow.setSizePolicy(sizePolicy)
        pcMainWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(pcMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton_4 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout.addWidget(self.toolButton_4, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.labelSeriesFilename = QtGui.QLabel(self.centralwidget)
        self.labelSeriesFilename.setObjectName(_fromUtf8("labelSeriesFilename"))
        self.gridLayout.addWidget(self.labelSeriesFilename, 0, 1, 1, 1)
        self.pbOpenFile = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbOpenFile.sizePolicy().hasHeightForWidth())
        self.pbOpenFile.setSizePolicy(sizePolicy)
        self.pbOpenFile.setObjectName(_fromUtf8("pbOpenFile"))
        self.gridLayout.addWidget(self.pbOpenFile, 2, 0, 1, 1)
        self.pbBeamBlank = QtGui.QPushButton(self.centralwidget)
        self.pbBeamBlank.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBeamBlank.sizePolicy().hasHeightForWidth())
        self.pbBeamBlank.setSizePolicy(sizePolicy)
        self.pbBeamBlank.setCheckable(True)
        self.pbBeamBlank.setChecked(False)
        self.pbBeamBlank.setObjectName(_fromUtf8("pbBeamBlank"))
        self.gridLayout.addWidget(self.pbBeamBlank, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pcTabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcTabWidget.sizePolicy().hasHeightForWidth())
        self.pcTabWidget.setSizePolicy(sizePolicy)
        self.pcTabWidget.setObjectName(_fromUtf8("pcTabWidget"))
        self.tabSetup = QtGui.QWidget()
        self.tabSetup.setObjectName(_fromUtf8("tabSetup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabSetup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.tabSetup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.leTempFileLocation = QtGui.QLineEdit(self.tabSetup)
        self.leTempFileLocation.setEnabled(False)
        self.leTempFileLocation.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.leTempFileLocation.setObjectName(_fromUtf8("leTempFileLocation"))
        self.gridLayout_4.addWidget(self.leTempFileLocation, 0, 1, 1, 1)
        self.pbPrintAll = QtGui.QPushButton(self.tabSetup)
        self.pbPrintAll.setObjectName(_fromUtf8("pbPrintAll"))
        self.gridLayout_4.addWidget(self.pbPrintAll, 1, 0, 1, 1)
        self.pcTabWidget.addTab(self.tabSetup, _fromUtf8(""))
        self.tabCalibration = QtGui.QWidget()
        self.tabCalibration.setObjectName(_fromUtf8("tabCalibration"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCalibration)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pbSetDLAperture = QtGui.QPushButton(self.tabCalibration)
        self.pbSetDLAperture.setCheckable(True)
        self.pbSetDLAperture.setObjectName(_fromUtf8("pbSetDLAperture"))
        self.gridLayout_2.addWidget(self.pbSetDLAperture, 12, 3, 1, 1)
        self.pbAcquireVacuumDiff = QtGui.QPushButton(self.tabCalibration)
        self.pbAcquireVacuumDiff.setObjectName(_fromUtf8("pbAcquireVacuumDiff"))
        self.gridLayout_2.addWidget(self.pbAcquireVacuumDiff, 14, 3, 1, 1)
        self.rbLoadOffsetDiff = QtGui.QRadioButton(self.tabCalibration)
        self.rbLoadOffsetDiff.setAutoExclusive(False)
        self.rbLoadOffsetDiff.setObjectName(_fromUtf8("rbLoadOffsetDiff"))
        self.gridLayout_2.addWidget(self.rbLoadOffsetDiff, 10, 3, 1, 1)
        self.sbTargetCountsDiff = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbTargetCountsDiff.setDecimals(0)
        self.sbTargetCountsDiff.setMaximum(60000.0)
        self.sbTargetCountsDiff.setSingleStep(1000.0)
        self.sbTargetCountsDiff.setProperty("value", 3000.0)
        self.sbTargetCountsDiff.setObjectName(_fromUtf8("sbTargetCountsDiff"))
        self.gridLayout_2.addWidget(self.sbTargetCountsDiff, 11, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.tabCalibration)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 11, 2, 1, 1)
        self.cbCloseColumnValve = QtGui.QCheckBox(self.tabCalibration)
        self.cbCloseColumnValve.setObjectName(_fromUtf8("cbCloseColumnValve"))
        self.gridLayout_2.addWidget(self.cbCloseColumnValve, 20, 1, 1, 1)
        self.rbProbeSeries = QtGui.QRadioButton(self.tabCalibration)
        self.rbProbeSeries.setChecked(True)
        self.rbProbeSeries.setObjectName(_fromUtf8("rbProbeSeries"))
        self.gridLayout_2.addWidget(self.rbProbeSeries, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sbFrameAverage = QtGui.QSpinBox(self.tabCalibration)
        self.sbFrameAverage.setMinimum(1)
        self.sbFrameAverage.setObjectName(_fromUtf8("sbFrameAverage"))
        self.gridLayout_2.addWidget(self.sbFrameAverage, 1, 1, 1, 1)
        self.cbCenteringMethod = QtGui.QComboBox(self.tabCalibration)
        self.cbCenteringMethod.setObjectName(_fromUtf8("cbCenteringMethod"))
        self.cbCenteringMethod.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cbCenteringMethod, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabCalibration)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sbBinning = QtGui.QSpinBox(self.tabCalibration)
        self.sbBinning.setMinimum(1)
        self.sbBinning.setMaximum(8)
        self.sbBinning.setProperty("value", 2)
        self.sbBinning.setObjectName(_fromUtf8("sbBinning"))
        self.gridLayout_2.addWidget(self.sbBinning, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabCalibration)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.cbFindOffsetsDiff = QtGui.QCheckBox(self.tabCalibration)
        self.cbFindOffsetsDiff.setChecked(True)
        self.cbFindOffsetsDiff.setObjectName(_fromUtf8("cbFindOffsetsDiff"))
        self.gridLayout_2.addWidget(self.cbFindOffsetsDiff, 9, 2, 1, 1)
        self.cbFindOffsetsProbe = QtGui.QCheckBox(self.tabCalibration)
        self.cbFindOffsetsProbe.setChecked(True)
        self.cbFindOffsetsProbe.setObjectName(_fromUtf8("cbFindOffsetsProbe"))
        self.gridLayout_2.addWidget(self.cbFindOffsetsProbe, 9, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sbIntensityStart = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbIntensityStart.setDecimals(4)
        self.sbIntensityStart.setMinimum(-99.99)
        self.sbIntensityStart.setSingleStep(0.01)
        self.sbIntensityStart.setProperty("value", -0.25)
        self.sbIntensityStart.setObjectName(_fromUtf8("sbIntensityStart"))
        self.gridLayout_2.addWidget(self.sbIntensityStart, 6, 1, 1, 1)
        self.pbAcquireSeries = QtGui.QPushButton(self.tabCalibration)
        self.pbAcquireSeries.setObjectName(_fromUtf8("pbAcquireSeries"))
        self.gridLayout_2.addWidget(self.pbAcquireSeries, 20, 0, 1, 1)
        self.sbTestBinning = QtGui.QSpinBox(self.tabCalibration)
        self.sbTestBinning.setMinimum(1)
        self.sbTestBinning.setMaximum(8)
        self.sbTestBinning.setProperty("value", 4)
        self.sbTestBinning.setObjectName(_fromUtf8("sbTestBinning"))
        self.gridLayout_2.addWidget(self.sbTestBinning, 3, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.tabCalibration)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tabCalibration)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_7 = QtGui.QLabel(self.tabCalibration)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_11 = QtGui.QLabel(self.tabCalibration)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 7, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabCalibration)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabCalibration)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 6, 2, 1, 1)
        self.sbIntensityEnd = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbIntensityEnd.setDecimals(4)
        self.sbIntensityEnd.setSingleStep(0.01)
        self.sbIntensityEnd.setProperty("value", 0.07)
        self.sbIntensityEnd.setObjectName(_fromUtf8("sbIntensityEnd"))
        self.gridLayout_2.addWidget(self.sbIntensityEnd, 7, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabCalibration)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_12 = QtGui.QLabel(self.tabCalibration)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 8, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tabCalibration)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 12, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sbTargetCountsProbe = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbTargetCountsProbe.setDecimals(0)
        self.sbTargetCountsProbe.setMaximum(60000.0)
        self.sbTargetCountsProbe.setSingleStep(1000.0)
        self.sbTargetCountsProbe.setProperty("value", 2000.0)
        self.sbTargetCountsProbe.setObjectName(_fromUtf8("sbTargetCountsProbe"))
        self.gridLayout_2.addWidget(self.sbTargetCountsProbe, 12, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tabCalibration)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 2, 1, 1)
        self.sbDiffStart = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbDiffStart.setMinimum(-999.0)
        self.sbDiffStart.setMaximum(999.0)
        self.sbDiffStart.setProperty("value", 145.0)
        self.sbDiffStart.setObjectName(_fromUtf8("sbDiffStart"))
        self.gridLayout_2.addWidget(self.sbDiffStart, 6, 3, 1, 1)
        self.rbDiffSeries = QtGui.QRadioButton(self.tabCalibration)
        self.rbDiffSeries.setChecked(False)
        self.rbDiffSeries.setObjectName(_fromUtf8("rbDiffSeries"))
        self.gridLayout_2.addWidget(self.rbDiffSeries, 4, 2, 1, 1)
        self.cbLoadOffsetsProbe = QtGui.QCheckBox(self.tabCalibration)
        self.cbLoadOffsetsProbe.setObjectName(_fromUtf8("cbLoadOffsetsProbe"))
        self.gridLayout_2.addWidget(self.cbLoadOffsetsProbe, 10, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sbTestDiffShift = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbTestDiffShift.setDecimals(5)
        self.sbTestDiffShift.setMaximum(1.0)
        self.sbTestDiffShift.setSingleStep(0.001)
        self.sbTestDiffShift.setProperty("value", 0.005)
        self.sbTestDiffShift.setObjectName(_fromUtf8("sbTestDiffShift"))
        self.gridLayout_2.addWidget(self.sbTestDiffShift, 2, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.tabCalibration)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.cbLoadOffsetsDiff = QtGui.QCheckBox(self.tabCalibration)
        self.cbLoadOffsetsDiff.setObjectName(_fromUtf8("cbLoadOffsetsDiff"))
        self.gridLayout_2.addWidget(self.cbLoadOffsetsDiff, 10, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabCalibration)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.sbTestTx = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbTestTx.setSingleStep(0.01)
        self.sbTestTx.setProperty("value", 0.1)
        self.sbTestTx.setObjectName(_fromUtf8("sbTestTx"))
        self.gridLayout_2.addWidget(self.sbTestTx, 0, 3, 1, 1)
        self.rbSaveOffsetsProbe = QtGui.QRadioButton(self.tabCalibration)
        self.rbSaveOffsetsProbe.setObjectName(_fromUtf8("rbSaveOffsetsProbe"))
        self.gridLayout_2.addWidget(self.rbSaveOffsetsProbe, 11, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_20 = QtGui.QLabel(self.tabCalibration)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 2, 0, 1, 1)
        self.sbDiffSteps = QtGui.QSpinBox(self.tabCalibration)
        self.sbDiffSteps.setMinimum(1)
        self.sbDiffSteps.setProperty("value", 33)
        self.sbDiffSteps.setObjectName(_fromUtf8("sbDiffSteps"))
        self.gridLayout_2.addWidget(self.sbDiffSteps, 8, 3, 1, 1)
        self.sbTestBeamShift = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbTestBeamShift.setDecimals(1)
        self.sbTestBeamShift.setMaximum(1000.0)
        self.sbTestBeamShift.setSingleStep(1.0)
        self.sbTestBeamShift.setProperty("value", 30.0)
        self.sbTestBeamShift.setObjectName(_fromUtf8("sbTestBeamShift"))
        self.gridLayout_2.addWidget(self.sbTestBeamShift, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabCalibration)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabCalibration)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.sbMaxTx = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbMaxTx.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.sbMaxTx.setProperty("value", 5.0)
        self.sbMaxTx.setObjectName(_fromUtf8("sbMaxTx"))
        self.gridLayout_2.addWidget(self.sbMaxTx, 0, 1, 1, 1)
        self.sbIntensitySteps = QtGui.QSpinBox(self.tabCalibration)
        self.sbIntensitySteps.setProperty("value", 33)
        self.sbIntensitySteps.setObjectName(_fromUtf8("sbIntensitySteps"))
        self.gridLayout_2.addWidget(self.sbIntensitySteps, 8, 1, 1, 1)
        self.sbDiffEnd = QtGui.QDoubleSpinBox(self.tabCalibration)
        self.sbDiffEnd.setMinimum(-999.0)
        self.sbDiffEnd.setMaximum(999.0)
        self.sbDiffEnd.setProperty("value", -70.0)
        self.sbDiffEnd.setObjectName(_fromUtf8("sbDiffEnd"))
        self.gridLayout_2.addWidget(self.sbDiffEnd, 7, 3, 1, 1)
        self.pbTestGotoStart = QtGui.QPushButton(self.tabCalibration)
        self.pbTestGotoStart.setObjectName(_fromUtf8("pbTestGotoStart"))
        self.gridLayout_2.addWidget(self.pbTestGotoStart, 14, 0, 1, 1)
        self.pbDescanBS = QtGui.QPushButton(self.tabCalibration)
        self.pbDescanBS.setObjectName(_fromUtf8("pbDescanBS"))
        self.gridLayout_2.addWidget(self.pbDescanBS, 19, 0, 1, 1)
        self.pbTestGotoEnd = QtGui.QPushButton(self.tabCalibration)
        self.pbTestGotoEnd.setObjectName(_fromUtf8("pbTestGotoEnd"))
        self.gridLayout_2.addWidget(self.pbTestGotoEnd, 16, 0, 1, 1)
        self.labelIntensity = QtGui.QLabel(self.tabCalibration)
        self.labelIntensity.setObjectName(_fromUtf8("labelIntensity"))
        self.gridLayout_2.addWidget(self.labelIntensity, 20, 3, 1, 1)
        self.rbSaveOffsetsDiff = QtGui.QRadioButton(self.tabCalibration)
        self.rbSaveOffsetsDiff.setAutoExclusive(False)
        self.rbSaveOffsetsDiff.setObjectName(_fromUtf8("rbSaveOffsetsDiff"))
        self.gridLayout_2.addWidget(self.rbSaveOffsetsDiff, 9, 3, 1, 1)
        self.pbAcquireCrystalDiff = QtGui.QPushButton(self.tabCalibration)
        self.pbAcquireCrystalDiff.setObjectName(_fromUtf8("pbAcquireCrystalDiff"))
        self.gridLayout_2.addWidget(self.pbAcquireCrystalDiff, 16, 3, 1, 1)
        self.pbManualDiff = QtGui.QPushButton(self.tabCalibration)
        self.pbManualDiff.setCheckable(True)
        self.pbManualDiff.setChecked(False)
        self.pbManualDiff.setObjectName(_fromUtf8("pbManualDiff"))
        self.gridLayout_2.addWidget(self.pbManualDiff, 20, 2, 1, 1)
        self.pbSetDLFocus = QtGui.QPushButton(self.tabCalibration)
        self.pbSetDLFocus.setCheckable(True)
        self.pbSetDLFocus.setObjectName(_fromUtf8("pbSetDLFocus"))
        self.gridLayout_2.addWidget(self.pbSetDLFocus, 12, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 17, 2, 1, 1)
        self.pbPrevIntensity = QtGui.QPushButton(self.tabCalibration)
        self.pbPrevIntensity.setObjectName(_fromUtf8("pbPrevIntensity"))
        self.gridLayout_2.addWidget(self.pbPrevIntensity, 19, 2, 1, 1)
        self.pbNextIntensity = QtGui.QPushButton(self.tabCalibration)
        self.pbNextIntensity.setObjectName(_fromUtf8("pbNextIntensity"))
        self.gridLayout_2.addWidget(self.pbNextIntensity, 19, 3, 1, 1)
        self.pbGotoDLAperture = QtGui.QPushButton(self.tabCalibration)
        self.pbGotoDLAperture.setObjectName(_fromUtf8("pbGotoDLAperture"))
        self.gridLayout_2.addWidget(self.pbGotoDLAperture, 13, 3, 1, 1)
        self.pbGotoDLFocus = QtGui.QPushButton(self.tabCalibration)
        self.pbGotoDLFocus.setObjectName(_fromUtf8("pbGotoDLFocus"))
        self.gridLayout_2.addWidget(self.pbGotoDLFocus, 13, 2, 1, 1)
        self.pbDescanDS = QtGui.QPushButton(self.tabCalibration)
        self.pbDescanDS.setObjectName(_fromUtf8("pbDescanDS"))
        self.gridLayout_2.addWidget(self.pbDescanDS, 19, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.pcTabWidget.addTab(self.tabCalibration, _fromUtf8(""))
        self.tabControl = QtGui.QWidget()
        self.tabControl.setObjectName(_fromUtf8("tabControl"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabControl)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pbBFScan = QtGui.QPushButton(self.tabControl)
        self.pbBFScan.setObjectName(_fromUtf8("pbBFScan"))
        self.gridLayout_6.addWidget(self.pbBFScan, 11, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tabControl)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 8, 1, 1, 1)
        self.sbXScanCount = QtGui.QSpinBox(self.tabControl)
        self.sbXScanCount.setMinimum(1)
        self.sbXScanCount.setMaximum(999)
        self.sbXScanCount.setProperty("value", 91)
        self.sbXScanCount.setObjectName(_fromUtf8("sbXScanCount"))
        self.gridLayout_6.addWidget(self.sbXScanCount, 2, 5, 1, 1)
        self.pbPtychoCalcPos = QtGui.QPushButton(self.tabControl)
        self.pbPtychoCalcPos.setObjectName(_fromUtf8("pbPtychoCalcPos"))
        self.gridLayout_6.addWidget(self.pbPtychoCalcPos, 5, 3, 1, 1)
        self.labelYAxis = QtGui.QLabel(self.tabControl)
        self.labelYAxis.setObjectName(_fromUtf8("labelYAxis"))
        self.gridLayout_6.addWidget(self.labelYAxis, 3, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self.tabControl)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_6.addWidget(self.label_22, 2, 4, 1, 1)
        self.rbPtychoDiffScan = QtGui.QRadioButton(self.tabControl)
        self.rbPtychoDiffScan.setChecked(False)
        self.rbPtychoDiffScan.setObjectName(_fromUtf8("rbPtychoDiffScan"))
        self.gridLayout_6.addWidget(self.rbPtychoDiffScan, 0, 3, 1, 1)
        self.sbYScanCount = QtGui.QSpinBox(self.tabControl)
        self.sbYScanCount.setEnabled(False)
        self.sbYScanCount.setMinimum(1)
        self.sbYScanCount.setMaximum(500)
        self.sbYScanCount.setProperty("value", 9)
        self.sbYScanCount.setObjectName(_fromUtf8("sbYScanCount"))
        self.gridLayout_6.addWidget(self.sbYScanCount, 3, 5, 1, 1)
        self.labelXAxis = QtGui.QLabel(self.tabControl)
        self.labelXAxis.setObjectName(_fromUtf8("labelXAxis"))
        self.gridLayout_6.addWidget(self.labelXAxis, 3, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbPtychoProbeScan = QtGui.QRadioButton(self.tabControl)
        self.rbPtychoProbeScan.setChecked(False)
        self.rbPtychoProbeScan.setObjectName(_fromUtf8("rbPtychoProbeScan"))
        self.gridLayout_5.addWidget(self.rbPtychoProbeScan, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.sbScanStep = QtGui.QDoubleSpinBox(self.tabControl)
        self.sbScanStep.setMaximum(500.0)
        self.sbScanStep.setProperty("value", 3.0)
        self.sbScanStep.setObjectName(_fromUtf8("sbScanStep"))
        self.gridLayout_6.addWidget(self.sbScanStep, 3, 3, 1, 1)
        self.cbScanPatType = QtGui.QComboBox(self.tabControl)
        self.cbScanPatType.setObjectName(_fromUtf8("cbScanPatType"))
        self.cbScanPatType.addItem(_fromUtf8(""))
        self.cbScanPatType.addItem(_fromUtf8(""))
        self.cbScanPatType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbScanPatType, 2, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.tabControl)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 10, 4, 1, 1)
        self.sbFastTx = QtGui.QDoubleSpinBox(self.tabControl)
        self.sbFastTx.setSingleStep(0.01)
        self.sbFastTx.setProperty("value", 0.01)
        self.sbFastTx.setObjectName(_fromUtf8("sbFastTx"))
        self.gridLayout_6.addWidget(self.sbFastTx, 9, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 13, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.tabControl)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 10, 1, 1, 1)
        self.sbPtychoTx = QtGui.QDoubleSpinBox(self.tabControl)
        self.sbPtychoTx.setSingleStep(0.1)
        self.sbPtychoTx.setProperty("value", 1.0)
        self.sbPtychoTx.setObjectName(_fromUtf8("sbPtychoTx"))
        self.gridLayout_6.addWidget(self.sbPtychoTx, 4, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.tabControl)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 2, 1, 1, 1)
        self.pbPtychoEstimateDose = QtGui.QPushButton(self.tabControl)
        self.pbPtychoEstimateDose.setObjectName(_fromUtf8("pbPtychoEstimateDose"))
        self.gridLayout_6.addWidget(self.pbPtychoEstimateDose, 6, 3, 1, 1)
        self.sbFastIntRadius = QtGui.QSpinBox(self.tabControl)
        self.sbFastIntRadius.setMinimum(1)
        self.sbFastIntRadius.setProperty("value", 20)
        self.sbFastIntRadius.setObjectName(_fromUtf8("sbFastIntRadius"))
        self.gridLayout_6.addWidget(self.sbFastIntRadius, 10, 5, 1, 1)
        self.cbFastFrameSize = QtGui.QComboBox(self.tabControl)
        self.cbFastFrameSize.setObjectName(_fromUtf8("cbFastFrameSize"))
        self.cbFastFrameSize.addItem(_fromUtf8(""))
        self.cbFastFrameSize.addItem(_fromUtf8(""))
        self.cbFastFrameSize.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbFastFrameSize, 10, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.tabControl)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 9, 4, 1, 1)
        self.sbFastBinning = QtGui.QSpinBox(self.tabControl)
        self.sbFastBinning.setMinimum(1)
        self.sbFastBinning.setMaximum(8)
        self.sbFastBinning.setProperty("value", 8)
        self.sbFastBinning.setObjectName(_fromUtf8("sbFastBinning"))
        self.gridLayout_6.addWidget(self.sbFastBinning, 9, 3, 1, 1)
        self.label_35 = QtGui.QLabel(self.tabControl)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 11, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.tabControl)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_6.addWidget(self.label_24, 4, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.tabControl)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 9, 1, 1, 1)
        self.pbZeroBSDS = QtGui.QPushButton(self.tabControl)
        self.pbZeroBSDS.setObjectName(_fromUtf8("pbZeroBSDS"))
        self.gridLayout_6.addWidget(self.pbZeroBSDS, 5, 5, 1, 1)
        self.pbAcquirePtycho = QtGui.QPushButton(self.tabControl)
        self.pbAcquirePtycho.setObjectName(_fromUtf8("pbAcquirePtycho"))
        self.gridLayout_6.addWidget(self.pbAcquirePtycho, 14, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.tabControl)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 7, 1, 1, 1)
        self.leDSetName = QtGui.QLineEdit(self.tabControl)
        self.leDSetName.setObjectName(_fromUtf8("leDSetName"))
        self.gridLayout_6.addWidget(self.leDSetName, 7, 3, 1, 1)
        self.pbBFCancel = QtGui.QPushButton(self.tabControl)
        self.pbBFCancel.setObjectName(_fromUtf8("pbBFCancel"))
        self.gridLayout_6.addWidget(self.pbBFCancel, 12, 1, 1, 1)
        self.rbPtychoUseIBS = QtGui.QRadioButton(self.tabControl)
        self.rbPtychoUseIBS.setChecked(True)
        self.rbPtychoUseIBS.setAutoExclusive(False)
        self.rbPtychoUseIBS.setObjectName(_fromUtf8("rbPtychoUseIBS"))
        self.gridLayout_6.addWidget(self.rbPtychoUseIBS, 1, 1, 1, 1)
        self.rbPtychoUseBSDS = QtGui.QRadioButton(self.tabControl)
        self.rbPtychoUseBSDS.setAutoExclusive(False)
        self.rbPtychoUseBSDS.setObjectName(_fromUtf8("rbPtychoUseBSDS"))
        self.gridLayout_6.addWidget(self.rbPtychoUseBSDS, 1, 3, 1, 1)
        self.pbPlotScanPositions = QtGui.QPushButton(self.tabControl)
        self.pbPlotScanPositions.setObjectName(_fromUtf8("pbPlotScanPositions"))
        self.gridLayout_6.addWidget(self.pbPlotScanPositions, 6, 4, 1, 1)
        self.cbRandomShift = QtGui.QCheckBox(self.tabControl)
        self.cbRandomShift.setObjectName(_fromUtf8("cbRandomShift"))
        self.gridLayout_6.addWidget(self.cbRandomShift, 4, 4, 1, 1)
        self.sbRandomShift = QtGui.QDoubleSpinBox(self.tabControl)
        self.sbRandomShift.setSingleStep(0.1)
        self.sbRandomShift.setProperty("value", 0.2)
        self.sbRandomShift.setObjectName(_fromUtf8("sbRandomShift"))
        self.gridLayout_6.addWidget(self.sbRandomShift, 4, 5, 1, 1)
        self.pcTabWidget.addTab(self.tabControl, _fromUtf8(""))
        self.tabImageRot = QtGui.QWidget()
        self.tabImageRot.setObjectName(_fromUtf8("tabImageRot"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabImageRot)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 521))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.sbRotMagDiff = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.sbRotMagDiff.setDecimals(0)
        self.sbRotMagDiff.setProperty("value", 11.0)
        self.sbRotMagDiff.setObjectName(_fromUtf8("sbRotMagDiff"))
        self.gridLayout_7.addWidget(self.sbRotMagDiff, 6, 1, 1, 1)
        self.pbRotTestDescan = QtGui.QPushButton(self.gridLayoutWidget)
        self.pbRotTestDescan.setObjectName(_fromUtf8("pbRotTestDescan"))
        self.gridLayout_7.addWidget(self.pbRotTestDescan, 10, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 2, 0, 1, 1)
        self.sbRotDSDescan = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.sbRotDSDescan.setProperty("value", 2.5)
        self.sbRotDSDescan.setObjectName(_fromUtf8("sbRotDSDescan"))
        self.gridLayout_7.addWidget(self.sbRotDSDescan, 4, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_7.addWidget(self.label_26, 3, 0, 1, 1)
        self.pbRotLoad = QtGui.QPushButton(self.gridLayoutWidget)
        self.pbRotLoad.setObjectName(_fromUtf8("pbRotLoad"))
        self.gridLayout_7.addWidget(self.pbRotLoad, 14, 1, 1, 1)
        self.sbRotMagImage = QtGui.QSpinBox(self.gridLayoutWidget)
        self.sbRotMagImage.setEnabled(True)
        self.sbRotMagImage.setMaximum(10000000)
        self.sbRotMagImage.setProperty("value", 32)
        self.sbRotMagImage.setObjectName(_fromUtf8("sbRotMagImage"))
        self.gridLayout_7.addWidget(self.sbRotMagImage, 5, 1, 1, 1)
        self.sbRotBSImage = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.sbRotBSImage.setDecimals(1)
        self.sbRotBSImage.setMaximum(1000.0)
        self.sbRotBSImage.setProperty("value", 25.0)
        self.sbRotBSImage.setObjectName(_fromUtf8("sbRotBSImage"))
        self.gridLayout_7.addWidget(self.sbRotBSImage, 2, 1, 1, 1)
        self.labelRotCali = QtGui.QLabel(self.gridLayoutWidget)
        self.labelRotCali.setObjectName(_fromUtf8("labelRotCali"))
        self.gridLayout_7.addWidget(self.labelRotCali, 1, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 6, 0, 1, 1)
        self.sbRotBSDiff = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.sbRotBSDiff.setDecimals(1)
        self.sbRotBSDiff.setMaximum(10000.0)
        self.sbRotBSDiff.setProperty("value", 50.0)
        self.sbRotBSDiff.setObjectName(_fromUtf8("sbRotBSDiff"))
        self.gridLayout_7.addWidget(self.sbRotBSDiff, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 12, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_7.addWidget(self.label_30, 4, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_7.addWidget(self.label_29, 7, 0, 1, 1)
        self.pbRotUpdate = QtGui.QPushButton(self.gridLayoutWidget)
        self.pbRotUpdate.setObjectName(_fromUtf8("pbRotUpdate"))
        self.gridLayout_7.addWidget(self.pbRotUpdate, 8, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.pbRotCalibrate = QtGui.QPushButton(self.gridLayoutWidget)
        self.pbRotCalibrate.setObjectName(_fromUtf8("pbRotCalibrate"))
        self.gridLayout_7.addWidget(self.pbRotCalibrate, 11, 1, 1, 1)
        self.pbRotSave = QtGui.QPushButton(self.gridLayoutWidget)
        self.pbRotSave.setObjectName(_fromUtf8("pbRotSave"))
        self.gridLayout_7.addWidget(self.pbRotSave, 13, 1, 1, 1)
        self.pcTabWidget.addTab(self.tabImageRot, _fromUtf8(""))
        self.tabDualSpace = QtGui.QWidget()
        self.tabDualSpace.setObjectName(_fromUtf8("tabDualSpace"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabDualSpace)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 511))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pbSaveVacuumArea = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbSaveVacuumArea.setCheckable(True)
        self.pbSaveVacuumArea.setObjectName(_fromUtf8("pbSaveVacuumArea"))
        self.gridLayout_8.addWidget(self.pbSaveVacuumArea, 2, 4, 1, 1)
        self.pbDSAquireSeries = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDSAquireSeries.sizePolicy().hasHeightForWidth())
        self.pbDSAquireSeries.setSizePolicy(sizePolicy)
        self.pbDSAquireSeries.setObjectName(_fromUtf8("pbDSAquireSeries"))
        self.gridLayout_8.addWidget(self.pbDSAquireSeries, 14, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 4, 1, 1, 1)
        self.cbDSDoCentering = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbDSDoCentering.setText(_fromUtf8(""))
        self.cbDSDoCentering.setChecked(False)
        self.cbDSDoCentering.setObjectName(_fromUtf8("cbDSDoCentering"))
        self.gridLayout_8.addWidget(self.cbDSDoCentering, 6, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_8.addWidget(self.label_39, 2, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_8.addWidget(self.label_41, 5, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_44.setText(_fromUtf8(""))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 7, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 9, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_8.addWidget(self.label_42, 3, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_8.addWidget(self.label_43, 8, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_47.setText(_fromUtf8(""))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_8.addWidget(self.label_47, 12, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 10, 1, 1, 1)
        self.cbDSDoDoubleExp = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbDSDoDoubleExp.setText(_fromUtf8(""))
        self.cbDSDoDoubleExp.setChecked(True)
        self.cbDSDoDoubleExp.setObjectName(_fromUtf8("cbDSDoDoubleExp"))
        self.gridLayout_8.addWidget(self.cbDSDoDoubleExp, 4, 2, 1, 1)
        self.sbDSDiffExposure = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDSDiffExposure.sizePolicy().hasHeightForWidth())
        self.sbDSDiffExposure.setSizePolicy(sizePolicy)
        self.sbDSDiffExposure.setDecimals(3)
        self.sbDSDiffExposure.setSingleStep(0.1)
        self.sbDSDiffExposure.setProperty("value", 0.1)
        self.sbDSDiffExposure.setObjectName(_fromUtf8("sbDSDiffExposure"))
        self.gridLayout_8.addWidget(self.sbDSDiffExposure, 2, 2, 1, 1)
        self.sbDSDiffSeriesLength = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sbDSDiffSeriesLength.setSingleStep(1)
        self.sbDSDiffSeriesLength.setProperty("value", 10)
        self.sbDSDiffSeriesLength.setObjectName(_fromUtf8("sbDSDiffSeriesLength"))
        self.gridLayout_8.addWidget(self.sbDSDiffSeriesLength, 3, 2, 1, 1)
        self.sbDSImageExposure = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.sbDSImageExposure.setProperty("value", 2.0)
        self.sbDSImageExposure.setObjectName(_fromUtf8("sbDSImageExposure"))
        self.gridLayout_8.addWidget(self.sbDSImageExposure, 8, 2, 1, 1)
        self.sbDSDoubleExposure = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.sbDSDoubleExposure.setDecimals(3)
        self.sbDSDoubleExposure.setSingleStep(0.1)
        self.sbDSDoubleExposure.setProperty("value", 2.0)
        self.sbDSDoubleExposure.setObjectName(_fromUtf8("sbDSDoubleExposure"))
        self.gridLayout_8.addWidget(self.sbDSDoubleExposure, 5, 2, 1, 1)
        self.cbDSRetractAperture = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbDSRetractAperture.setText(_fromUtf8(""))
        self.cbDSRetractAperture.setChecked(False)
        self.cbDSRetractAperture.setAutoExclusive(True)
        self.cbDSRetractAperture.setObjectName(_fromUtf8("cbDSRetractAperture"))
        self.gridLayout_8.addWidget(self.cbDSRetractAperture, 10, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 7, 3, 1, 1)
        self.sbDSImageSeriesLength = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sbDSImageSeriesLength.setProperty("value", 3)
        self.sbDSImageSeriesLength.setObjectName(_fromUtf8("sbDSImageSeriesLength"))
        self.gridLayout_8.addWidget(self.sbDSImageSeriesLength, 9, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 15, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_8.addWidget(self.label_48, 6, 1, 1, 1)
        self.sbDSBinning = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sbDSBinning.setMinimum(1)
        self.sbDSBinning.setObjectName(_fromUtf8("sbDSBinning"))
        self.gridLayout_8.addWidget(self.sbDSBinning, 1, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 1, 1, 1, 1)
        self.labelVacX = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelVacX.setObjectName(_fromUtf8("labelVacX"))
        self.gridLayout_8.addWidget(self.labelVacX, 3, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 5, 5, 1, 1)
        self.labelVacY = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelVacY.setObjectName(_fromUtf8("labelVacY"))
        self.gridLayout_8.addWidget(self.labelVacY, 4, 4, 1, 1)
        self.labelVacZ = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelVacZ.setObjectName(_fromUtf8("labelVacZ"))
        self.gridLayout_8.addWidget(self.labelVacZ, 5, 4, 1, 1)
        self.pbGotoVacuumArea = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbGotoVacuumArea.setObjectName(_fromUtf8("pbGotoVacuumArea"))
        self.gridLayout_8.addWidget(self.pbGotoVacuumArea, 6, 4, 1, 1)
        self.pbSaveSpecimenArea = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbSaveSpecimenArea.setCheckable(True)
        self.pbSaveSpecimenArea.setObjectName(_fromUtf8("pbSaveSpecimenArea"))
        self.gridLayout_8.addWidget(self.pbSaveSpecimenArea, 8, 4, 1, 1)
        self.pbGotoSpecimenArea = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pbGotoSpecimenArea.setObjectName(_fromUtf8("pbGotoSpecimenArea"))
        self.gridLayout_8.addWidget(self.pbGotoSpecimenArea, 14, 4, 1, 1)
        self.labelSpecimenX = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSpecimenX.setObjectName(_fromUtf8("labelSpecimenX"))
        self.gridLayout_8.addWidget(self.labelSpecimenX, 9, 4, 1, 1)
        self.labelSpecimenY = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSpecimenY.setObjectName(_fromUtf8("labelSpecimenY"))
        self.gridLayout_8.addWidget(self.labelSpecimenY, 10, 4, 1, 1)
        self.label_50 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 11, 1, 1, 1)
        self.labelSpecimenZ = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSpecimenZ.setObjectName(_fromUtf8("labelSpecimenZ"))
        self.gridLayout_8.addWidget(self.labelSpecimenZ, 11, 4, 1, 1)
        self.cbProbeInVacuum = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbProbeInVacuum.setText(_fromUtf8(""))
        self.cbProbeInVacuum.setAutoExclusive(True)
        self.cbProbeInVacuum.setObjectName(_fromUtf8("cbProbeInVacuum"))
        self.gridLayout_8.addWidget(self.cbProbeInVacuum, 11, 2, 1, 1)
        self.pcTabWidget.addTab(self.tabDualSpace, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 751, 501))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.labelZemlinMaxTilt = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelZemlinMaxTilt.setObjectName(_fromUtf8("labelZemlinMaxTilt"))
        self.gridLayout_9.addWidget(self.labelZemlinMaxTilt, 5, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_9.addWidget(self.label_55, 7, 0, 1, 1)
        self.sbZemlinBinning = QtGui.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbZemlinBinning.sizePolicy().hasHeightForWidth())
        self.sbZemlinBinning.setSizePolicy(sizePolicy)
        self.sbZemlinBinning.setMinimum(1)
        self.sbZemlinBinning.setMaximum(8)
        self.sbZemlinBinning.setProperty("value", 1)
        self.sbZemlinBinning.setObjectName(_fromUtf8("sbZemlinBinning"))
        self.gridLayout_9.addWidget(self.sbZemlinBinning, 7, 1, 1, 1)
        self.sbZemlinTx = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbZemlinTx.sizePolicy().hasHeightForWidth())
        self.sbZemlinTx.setSizePolicy(sizePolicy)
        self.sbZemlinTx.setDecimals(3)
        self.sbZemlinTx.setSingleStep(0.25)
        self.sbZemlinTx.setProperty("value", 1.0)
        self.sbZemlinTx.setObjectName(_fromUtf8("sbZemlinTx"))
        self.gridLayout_9.addWidget(self.sbZemlinTx, 6, 1, 1, 1)
        self.sbZemlinTiltStep = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbZemlinTiltStep.sizePolicy().hasHeightForWidth())
        self.sbZemlinTiltStep.setSizePolicy(sizePolicy)
        self.sbZemlinTiltStep.setMaximum(500.0)
        self.sbZemlinTiltStep.setProperty("value", 3.0)
        self.sbZemlinTiltStep.setObjectName(_fromUtf8("sbZemlinTiltStep"))
        self.gridLayout_9.addWidget(self.sbZemlinTiltStep, 3, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_9.addWidget(self.label_51, 2, 0, 1, 1)
        self.rbZemlinUseBT = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.rbZemlinUseBT.setChecked(True)
        self.rbZemlinUseBT.setAutoExclusive(True)
        self.rbZemlinUseBT.setObjectName(_fromUtf8("rbZemlinUseBT"))
        self.gridLayout_9.addWidget(self.rbZemlinUseBT, 0, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_9.addWidget(self.label_54, 6, 0, 1, 1)
        self.labelXAxis_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXAxis_3.sizePolicy().hasHeightForWidth())
        self.labelXAxis_3.setSizePolicy(sizePolicy)
        self.labelXAxis_3.setObjectName(_fromUtf8("labelXAxis_3"))
        self.gridLayout_9.addWidget(self.labelXAxis_3, 5, 0, 1, 1)
        self.cbZemlinScanPatType = QtGui.QComboBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbZemlinScanPatType.sizePolicy().hasHeightForWidth())
        self.cbZemlinScanPatType.setSizePolicy(sizePolicy)
        self.cbZemlinScanPatType.setObjectName(_fromUtf8("cbZemlinScanPatType"))
        self.cbZemlinScanPatType.addItem(_fromUtf8(""))
        self.cbZemlinScanPatType.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cbZemlinScanPatType, 2, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_9.addWidget(self.label_53, 1, 0, 1, 1)
        self.rbZemlinUseIBT = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.rbZemlinUseIBT.setChecked(False)
        self.rbZemlinUseIBT.setAutoExclusive(True)
        self.rbZemlinUseIBT.setObjectName(_fromUtf8("rbZemlinUseIBT"))
        self.gridLayout_9.addWidget(self.rbZemlinUseIBT, 0, 1, 1, 1)
        self.labelXAxis_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelXAxis_2.setObjectName(_fromUtf8("labelXAxis_2"))
        self.gridLayout_9.addWidget(self.labelXAxis_2, 3, 0, 1, 1)
        self.sbZemlinTiltPos = QtGui.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbZemlinTiltPos.sizePolicy().hasHeightForWidth())
        self.sbZemlinTiltPos.setSizePolicy(sizePolicy)
        self.sbZemlinTiltPos.setMinimum(1)
        self.sbZemlinTiltPos.setMaximum(999)
        self.sbZemlinTiltPos.setProperty("value", 19)
        self.sbZemlinTiltPos.setObjectName(_fromUtf8("sbZemlinTiltPos"))
        self.gridLayout_9.addWidget(self.sbZemlinTiltPos, 1, 1, 1, 1)
        self.leZemlinDataName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leZemlinDataName.setObjectName(_fromUtf8("leZemlinDataName"))
        self.gridLayout_9.addWidget(self.leZemlinDataName, 8, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_9.addWidget(self.label_52, 8, 0, 1, 1)
        self.pbPlotZemlinTilts = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPlotZemlinTilts.sizePolicy().hasHeightForWidth())
        self.pbPlotZemlinTilts.setSizePolicy(sizePolicy)
        self.pbPlotZemlinTilts.setObjectName(_fromUtf8("pbPlotZemlinTilts"))
        self.gridLayout_9.addWidget(self.pbPlotZemlinTilts, 4, 1, 1, 1)
        self.pbZemlinAcquire = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbZemlinAcquire.sizePolicy().hasHeightForWidth())
        self.pbZemlinAcquire.setSizePolicy(sizePolicy)
        self.pbZemlinAcquire.setObjectName(_fromUtf8("pbZemlinAcquire"))
        self.gridLayout_9.addWidget(self.pbZemlinAcquire, 9, 1, 1, 1)
        self.pcTabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.pcTabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        pcMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pcMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMicroscope = QtGui.QMenu(self.menubar)
        self.menuMicroscope.setObjectName(_fromUtf8("menuMicroscope"))
        pcMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(pcMainWindow)
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setStyleSheet(_fromUtf8(""))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        pcMainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(pcMainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSimulator = QtGui.QAction(pcMainWindow)
        self.actionSimulator.setCheckable(True)
        self.actionSimulator.setObjectName(_fromUtf8("actionSimulator"))
        self.actionFEI_Titan = QtGui.QAction(pcMainWindow)
        self.actionFEI_Titan.setCheckable(True)
        self.actionFEI_Titan.setObjectName(_fromUtf8("actionFEI_Titan"))
        self.menuFile.addAction(self.actionQuit)
        self.menuMicroscope.addAction(self.actionSimulator)
        self.menuMicroscope.addAction(self.actionFEI_Titan)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMicroscope.menuAction())

        self.retranslateUi(pcMainWindow)
        self.pcTabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(pcMainWindow)

    def retranslateUi(self, pcMainWindow):
        pcMainWindow.setWindowTitle(_translate("pcMainWindow", "PtychoControl 0.3", None))
        self.toolButton_4.setText(_translate("pcMainWindow", "...", None))
        self.label_19.setText(_translate("pcMainWindow", "Series file name:", None))
        self.labelSeriesFilename.setText(_translate("pcMainWindow", "...", None))
        self.pbOpenFile.setText(_translate("pcMainWindow", "Open File", None))
        self.pbBeamBlank.setText(_translate("pcMainWindow", "Beam Blank", None))
        self.label.setText(_translate("pcMainWindow", "Temporary file location: ", None))
        self.leTempFileLocation.setText(_translate("pcMainWindow", "E:\\tempimage.tif", None))
        self.pbPrintAll.setText(_translate("pcMainWindow", "Print All Results", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tabSetup), _translate("pcMainWindow", "Setup", None))
        self.pbSetDLAperture.setText(_translate("pcMainWindow", "Set DL Aperture", None))
        self.pbAcquireVacuumDiff.setText(_translate("pcMainWindow", "Acquire Vacuum Diff", None))
        self.rbLoadOffsetDiff.setText(_translate("pcMainWindow", "Use stored offsets", None))
        self.label_14.setText(_translate("pcMainWindow", "Target counts:", None))
        self.cbCloseColumnValve.setText(_translate("pcMainWindow", "Close column valve at end", None))
        self.rbProbeSeries.setText(_translate("pcMainWindow", "Probe series ", None))
        self.cbCenteringMethod.setItemText(0, _translate("pcMainWindow", "Center of mass", None))
        self.label_8.setText(_translate("pcMainWindow", "End (m): ", None))
        self.label_5.setText(_translate("pcMainWindow", "Intensity Lens", None))
        self.cbFindOffsetsDiff.setText(_translate("pcMainWindow", "Find offsets (diffraction)", None))
        self.cbFindOffsetsProbe.setText(_translate("pcMainWindow", "Find offsets (probe) ", None))
        self.pbAcquireSeries.setText(_translate("pcMainWindow", "Acquire series", None))
        self.label_17.setText(_translate("pcMainWindow", "Test detector binning:", None))
        self.label_15.setText(_translate("pcMainWindow", "Detector binning: ", None))
        self.label_7.setText(_translate("pcMainWindow", "Start (m) ", None))
        self.label_11.setText(_translate("pcMainWindow", "End (um):", None))
        self.label_6.setText(_translate("pcMainWindow", "Diffraction Lens", None))
        self.label_10.setText(_translate("pcMainWindow", "Start (um):", None))
        self.label_9.setText(_translate("pcMainWindow", "No of steps: ", None))
        self.label_12.setText(_translate("pcMainWindow", "No of steps:", None))
        self.label_13.setText(_translate("pcMainWindow", "Target counts: ", None))
        self.label_16.setText(_translate("pcMainWindow", "Centering method:", None))
        self.rbDiffSeries.setText(_translate("pcMainWindow", "Diffraction series", None))
        self.cbLoadOffsetsProbe.setText(_translate("pcMainWindow", "Load offsets (probe)", None))
        self.label_18.setText(_translate("pcMainWindow", "Test Diffraction Shift:", None))
        self.cbLoadOffsetsDiff.setText(_translate("pcMainWindow", "Load offsets (diffraction)", None))
        self.label_2.setText(_translate("pcMainWindow", "Test exposure time (s): ", None))
        self.rbSaveOffsetsProbe.setText(_translate("pcMainWindow", "Store offsets in memory (probe)", None))
        self.label_20.setText(_translate("pcMainWindow", "Test beam shift (nm):", None))
        self.label_3.setText(_translate("pcMainWindow", "Max exposure time (s): ", None))
        self.label_4.setText(_translate("pcMainWindow", "Frame averaging: ", None))
        self.pbTestGotoStart.setText(_translate("pcMainWindow", "Test: go to Start", None))
        self.pbDescanBS.setText(_translate("pcMainWindow", "Descan BS", None))
        self.pbTestGotoEnd.setText(_translate("pcMainWindow", "Test: go to End", None))
        self.labelIntensity.setText(_translate("pcMainWindow", "Intensity: ", None))
        self.rbSaveOffsetsDiff.setText(_translate("pcMainWindow", "Store offsets in memory (diffraction)", None))
        self.pbAcquireCrystalDiff.setText(_translate("pcMainWindow", "Acquire Crystal Diff", None))
        self.pbManualDiff.setText(_translate("pcMainWindow", "Manual Diff START", None))
        self.pbSetDLFocus.setText(_translate("pcMainWindow", "Set DL Focus", None))
        self.pbPrevIntensity.setText(_translate("pcMainWindow", "Previous Intensity", None))
        self.pbNextIntensity.setText(_translate("pcMainWindow", "Next Intensity", None))
        self.pbGotoDLAperture.setText(_translate("pcMainWindow", "Goto DL Aperture", None))
        self.pbGotoDLFocus.setText(_translate("pcMainWindow", "Goto DL Focus", None))
        self.pbDescanDS.setText(_translate("pcMainWindow", "Descan DS", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tabCalibration), _translate("pcMainWindow", "Calibration", None))
        self.pbBFScan.setText(_translate("pcMainWindow", "Brightfield Scan", None))
        self.label_31.setText(_translate("pcMainWindow", "FAST SCAN PLOT", None))
        self.pbPtychoCalcPos.setText(_translate("pcMainWindow", "Calculate BS Positions", None))
        self.labelYAxis.setText(_translate("pcMainWindow", "Y-scan positions", None))
        self.label_22.setText(_translate("pcMainWindow", "X-scan positions ", None))
        self.rbPtychoDiffScan.setText(_translate("pcMainWindow", "Diffractogram scan", None))
        self.labelXAxis.setText(_translate("pcMainWindow", "Step size (nm): ", None))
        self.rbPtychoProbeScan.setText(_translate("pcMainWindow", "Probe scan", None))
        self.cbScanPatType.setItemText(0, _translate("pcMainWindow", "Hex", None))
        self.cbScanPatType.setItemText(1, _translate("pcMainWindow", "Fermat", None))
        self.cbScanPatType.setItemText(2, _translate("pcMainWindow", "Grid", None))
        self.label_36.setText(_translate("pcMainWindow", "Integration radius (pix):", None))
        self.label_34.setText(_translate("pcMainWindow", "Frame size:", None))
        self.label_21.setText(_translate("pcMainWindow", "Scan pattern: ", None))
        self.pbPtychoEstimateDose.setText(_translate("pcMainWindow", "Estimate Dose", None))
        self.cbFastFrameSize.setItemText(0, _translate("pcMainWindow", "Full", None))
        self.cbFastFrameSize.setItemText(1, _translate("pcMainWindow", "Half", None))
        self.cbFastFrameSize.setItemText(2, _translate("pcMainWindow", "Quarter", None))
        self.label_33.setText(_translate("pcMainWindow", "Fast exposure time (s):", None))
        self.label_35.setText(_translate("pcMainWindow", "Uses rotation calibration for descan", None))
        self.label_24.setText(_translate("pcMainWindow", "Exposure time (s): ", None))
        self.label_32.setText(_translate("pcMainWindow", "Fast binning:", None))
        self.pbZeroBSDS.setText(_translate("pcMainWindow", "Zero BS/DS", None))
        self.pbAcquirePtycho.setText(_translate("pcMainWindow", "Acquire Ptycho", None))
        self.label_37.setText(_translate("pcMainWindow", "Dataset name:", None))
        self.leDSetName.setText(_translate("pcMainWindow", "ptychoA", None))
        self.pbBFCancel.setText(_translate("pcMainWindow", "Cancel Scan", None))
        self.rbPtychoUseIBS.setText(_translate("pcMainWindow", "IBS", None))
        self.rbPtychoUseBSDS.setText(_translate("pcMainWindow", "BS / DS", None))
        self.pbPlotScanPositions.setText(_translate("pcMainWindow", "Plot Scan Positions", None))
        self.cbRandomShift.setText(_translate("pcMainWindow", "Random shift", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tabControl), _translate("pcMainWindow", "Control", None))
        self.pbRotTestDescan.setText(_translate("pcMainWindow", "Test Descan", None))
        self.label_25.setText(_translate("pcMainWindow", "Image beam shift (nm):", None))
        self.label_26.setText(_translate("pcMainWindow", "Diffraction beam shift (nm): ", None))
        self.pbRotLoad.setText(_translate("pcMainWindow", "Load Rotation Calibration", None))
        self.labelRotCali.setText(_translate("pcMainWindow", "UNCALIBRATED", None))
        self.label_23.setText(_translate("pcMainWindow", "Rotation calibration, image to diffraction (focus dependant):", None))
        self.label_28.setText(_translate("pcMainWindow", "Diffraction camera length (m):", None))
        self.label_27.setText(_translate("pcMainWindow", "Image magnification:", None))
        self.label_30.setText(_translate("pcMainWindow", "Diffraction diff shift descan (mm):", None))
        self.label_29.setText(_translate("pcMainWindow", "Remember to be out of Align Beam Shift mode! \n"
" Both beam and diff aligns should be fresh and the beam on the CCD", None))
        self.pbRotUpdate.setText(_translate("pcMainWindow", "Update from TEM", None))
        self.label_38.setText(_translate("pcMainWindow", "STATUS:", None))
        self.pbRotCalibrate.setText(_translate("pcMainWindow", "Rotation Calibration", None))
        self.pbRotSave.setText(_translate("pcMainWindow", "Save Rotation Calibration", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tabImageRot), _translate("pcMainWindow", "Rotation", None))
        self.pbSaveVacuumArea.setText(_translate("pcMainWindow", "Save Vacuum Area", None))
        self.pbDSAquireSeries.setText(_translate("pcMainWindow", "Acquire Dual-space Series", None))
        self.label_40.setText(_translate("pcMainWindow", "Do double exposure?", None))
        self.label_39.setText(_translate("pcMainWindow", "Diffraction exposure (s):", None))
        self.label_41.setText(_translate("pcMainWindow", "Double exposure (s):", None))
        self.label_45.setText(_translate("pcMainWindow", "Image series length: ", None))
        self.label_42.setText(_translate("pcMainWindow", "Diffraction series length:", None))
        self.label_43.setText(_translate("pcMainWindow", "Image exposure time: ", None))
        self.label_46.setText(_translate("pcMainWindow", "Retract small aperture?", None))
        self.label_48.setText(_translate("pcMainWindow", "Do Centering?", None))
        self.label_49.setText(_translate("pcMainWindow", "Binning:", None))
        self.labelVacX.setText(_translate("pcMainWindow", "X: ", None))
        self.labelVacY.setText(_translate("pcMainWindow", "Y:", None))
        self.labelVacZ.setText(_translate("pcMainWindow", "Z:", None))
        self.pbGotoVacuumArea.setText(_translate("pcMainWindow", "Goto Vacuum Area", None))
        self.pbSaveSpecimenArea.setText(_translate("pcMainWindow", "Save Specimen Area", None))
        self.pbGotoSpecimenArea.setText(_translate("pcMainWindow", "Goto Specimen Area", None))
        self.labelSpecimenX.setText(_translate("pcMainWindow", "X: ", None))
        self.labelSpecimenY.setText(_translate("pcMainWindow", "Y: ", None))
        self.label_50.setText(_translate("pcMainWindow", "Probe in vacuum?", None))
        self.labelSpecimenZ.setText(_translate("pcMainWindow", "Z: ", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tabDualSpace), _translate("pcMainWindow", "Dual-space", None))
        self.labelZemlinMaxTilt.setText(_translate("pcMainWindow", "0", None))
        self.label_55.setText(_translate("pcMainWindow", "Binning:", None))
        self.label_51.setText(_translate("pcMainWindow", "Scan pattern: ", None))
        self.rbZemlinUseBT.setText(_translate("pcMainWindow", "BT", None))
        self.label_54.setText(_translate("pcMainWindow", "Exposure time (s):", None))
        self.labelXAxis_3.setText(_translate("pcMainWindow", "Maximum tilt angle (mrad):", None))
        self.cbZemlinScanPatType.setItemText(0, _translate("pcMainWindow", "Hex", None))
        self.cbZemlinScanPatType.setItemText(1, _translate("pcMainWindow", "Fermat", None))
        self.label_53.setText(_translate("pcMainWindow", "Number of tilt positions: ", None))
        self.rbZemlinUseIBT.setText(_translate("pcMainWindow", "IBT", None))
        self.labelXAxis_2.setText(_translate("pcMainWindow", "Step size (mrad): ", None))
        self.leZemlinDataName.setText(_translate("pcMainWindow", "Zemlin", None))
        self.label_52.setText(_translate("pcMainWindow", "HDF5 data name:", None))
        self.pbPlotZemlinTilts.setText(_translate("pcMainWindow", "Plot Zemlin Tilts", None))
        self.pbZemlinAcquire.setText(_translate("pcMainWindow", "Acquire Zemlin Tableau", None))
        self.pcTabWidget.setTabText(self.pcTabWidget.indexOf(self.tab), _translate("pcMainWindow", "Zemlin", None))
        self.menuFile.setTitle(_translate("pcMainWindow", "File", None))
        self.menuMicroscope.setTitle(_translate("pcMainWindow", "Microscope", None))
        self.actionQuit.setText(_translate("pcMainWindow", "Quit", None))
        self.actionSimulator.setText(_translate("pcMainWindow", "Simulator", None))
        self.actionFEI_Titan.setText(_translate("pcMainWindow", "FEI Titan", None))

