# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\PtychoControl\pdaUI.ui'
#
# Created: Fri Apr 10 14:42:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DeflectorWindow(object):
    def setupUi(self, DeflectorWindow):
        DeflectorWindow.setObjectName(_fromUtf8("DeflectorWindow"))
        DeflectorWindow.resize(539, 818)
        self.centralwidget = QtGui.QWidget(DeflectorWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 541, 781))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridTop = QtGui.QGridLayout()
        self.gridTop.setObjectName(_fromUtf8("gridTop"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.rbDS = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbDS.sizePolicy().hasHeightForWidth())
        self.rbDS.setSizePolicy(sizePolicy)
        self.rbDS.setMinimumSize(QtCore.QSize(185, 0))
        self.rbDS.setChecked(False)
        self.rbDS.setObjectName(_fromUtf8("rbDS"))
        self.horizontalLayout_9.addWidget(self.rbDS)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_9.addWidget(self.label_22)
        self.sbDS_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbDS_X.setDecimals(4)
        self.sbDS_X.setMinimum(-100.0)
        self.sbDS_X.setMaximum(100.0)
        self.sbDS_X.setObjectName(_fromUtf8("sbDS_X"))
        self.horizontalLayout_9.addWidget(self.sbDS_X)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_9.addWidget(self.label_23)
        self.sbDS_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbDS_Y.setDecimals(4)
        self.sbDS_Y.setMinimum(-100.0)
        self.sbDS_Y.setMaximum(100.0)
        self.sbDS_Y.setObjectName(_fromUtf8("sbDS_Y"))
        self.horizontalLayout_9.addWidget(self.sbDS_Y)
        self.gridTop.addLayout(self.horizontalLayout_9, 12, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridTop.addWidget(self.line_3, 13, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rbBS = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbBS.sizePolicy().hasHeightForWidth())
        self.rbBS.setSizePolicy(sizePolicy)
        self.rbBS.setMinimumSize(QtCore.QSize(185, 0))
        self.rbBS.setChecked(True)
        self.rbBS.setObjectName(_fromUtf8("rbBS"))
        self.horizontalLayout_3.addWidget(self.rbBS)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.sbBS_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbBS_X.setDecimals(4)
        self.sbBS_X.setMinimum(-100.0)
        self.sbBS_X.setMaximum(100.0)
        self.sbBS_X.setSingleStep(1.0)
        self.sbBS_X.setObjectName(_fromUtf8("sbBS_X"))
        self.horizontalLayout_3.addWidget(self.sbBS_X)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.sbBS_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbBS_Y.setDecimals(4)
        self.sbBS_Y.setMinimum(-100.0)
        self.sbBS_Y.setMaximum(100.0)
        self.sbBS_Y.setSingleStep(1.0)
        self.sbBS_Y.setObjectName(_fromUtf8("sbBS_Y"))
        self.horizontalLayout_3.addWidget(self.sbBS_Y)
        self.gridTop.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridTop.addWidget(self.line_2, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rbIBT = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbIBT.sizePolicy().hasHeightForWidth())
        self.rbIBT.setSizePolicy(sizePolicy)
        self.rbIBT.setMinimumSize(QtCore.QSize(185, 0))
        self.rbIBT.setObjectName(_fromUtf8("rbIBT"))
        self.horizontalLayout_7.addWidget(self.rbIBT)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_7.addWidget(self.label_18)
        self.sbIBT_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIBT_X.setDecimals(4)
        self.sbIBT_X.setMinimum(-100.0)
        self.sbIBT_X.setMaximum(100.0)
        self.sbIBT_X.setProperty("value", 0.0)
        self.sbIBT_X.setObjectName(_fromUtf8("sbIBT_X"))
        self.horizontalLayout_7.addWidget(self.sbIBT_X)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_7.addWidget(self.label_19)
        self.sbIBT_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIBT_Y.setDecimals(4)
        self.sbIBT_Y.setMinimum(-100.0)
        self.sbIBT_Y.setMaximum(100.0)
        self.sbIBT_Y.setObjectName(_fromUtf8("sbIBT_Y"))
        self.horizontalLayout_7.addWidget(self.sbIBT_Y)
        self.gridTop.addLayout(self.horizontalLayout_7, 10, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbGT = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbGT.sizePolicy().hasHeightForWidth())
        self.rbGT.setSizePolicy(sizePolicy)
        self.rbGT.setMinimumSize(QtCore.QSize(185, 0))
        self.rbGT.setObjectName(_fromUtf8("rbGT"))
        self.horizontalLayout_2.addWidget(self.rbGT)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.sbGT_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbGT_X.setMinimum(-100.0)
        self.sbGT_X.setMaximum(100.0)
        self.sbGT_X.setSingleStep(1.0)
        self.sbGT_X.setObjectName(_fromUtf8("sbGT_X"))
        self.horizontalLayout_2.addWidget(self.sbGT_X)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sbGT_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbGT_Y.setMinimum(-100.0)
        self.sbGT_Y.setMaximum(100.0)
        self.sbGT_Y.setProperty("value", 0.0)
        self.sbGT_Y.setObjectName(_fromUtf8("sbGT_Y"))
        self.horizontalLayout_2.addWidget(self.sbGT_Y)
        self.gridTop.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridTop.addWidget(self.line, 3, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.sbStage_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStage_X.setDecimals(4)
        self.sbStage_X.setMinimum(-999.0)
        self.sbStage_X.setMaximum(999.0)
        self.sbStage_X.setSingleStep(3.0)
        self.sbStage_X.setObjectName(_fromUtf8("sbStage_X"))
        self.gridLayout.addWidget(self.sbStage_X, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)
        self.sbStage_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStage_Y.setDecimals(4)
        self.sbStage_Y.setMinimum(-999.0)
        self.sbStage_Y.setMaximum(999.0)
        self.sbStage_Y.setSingleStep(3.0)
        self.sbStage_Y.setObjectName(_fromUtf8("sbStage_Y"))
        self.gridLayout.addWidget(self.sbStage_Y, 0, 5, 1, 1)
        self.sbStage_Alpha = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStage_Alpha.setDecimals(4)
        self.sbStage_Alpha.setMinimum(-45.0)
        self.sbStage_Alpha.setMaximum(45.0)
        self.sbStage_Alpha.setSingleStep(0.5)
        self.sbStage_Alpha.setObjectName(_fromUtf8("sbStage_Alpha"))
        self.gridLayout.addWidget(self.sbStage_Alpha, 1, 3, 1, 1)
        self.sbStage_Beta = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStage_Beta.setDecimals(4)
        self.sbStage_Beta.setMinimum(-45.0)
        self.sbStage_Beta.setMaximum(45.0)
        self.sbStage_Beta.setSingleStep(0.5)
        self.sbStage_Beta.setObjectName(_fromUtf8("sbStage_Beta"))
        self.gridLayout.addWidget(self.sbStage_Beta, 1, 5, 1, 1)
        self.rbStage = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rbStage.setChecked(False)
        self.rbStage.setObjectName(_fromUtf8("rbStage"))
        self.gridLayout.addWidget(self.rbStage, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.sbStage_Z = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStage_Z.setDecimals(3)
        self.sbStage_Z.setMinimum(-300.0)
        self.sbStage_Z.setMaximum(300.0)
        self.sbStage_Z.setSingleStep(10.0)
        self.sbStage_Z.setObjectName(_fromUtf8("sbStage_Z"))
        self.gridLayout.addWidget(self.sbStage_Z, 1, 1, 1, 1)
        self.gridTop.addLayout(self.gridLayout, 14, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rbBT = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbBT.sizePolicy().hasHeightForWidth())
        self.rbBT.setSizePolicy(sizePolicy)
        self.rbBT.setMinimumSize(QtCore.QSize(185, 0))
        self.rbBT.setObjectName(_fromUtf8("rbBT"))
        self.horizontalLayout_4.addWidget(self.rbBT)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.sbBT_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbBT_X.setDecimals(4)
        self.sbBT_X.setMinimum(-100.0)
        self.sbBT_X.setMaximum(100.0)
        self.sbBT_X.setSingleStep(0.1)
        self.sbBT_X.setObjectName(_fromUtf8("sbBT_X"))
        self.horizontalLayout_4.addWidget(self.sbBT_X)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.sbBT_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbBT_Y.setDecimals(4)
        self.sbBT_Y.setMinimum(-100.0)
        self.sbBT_Y.setMaximum(100.0)
        self.sbBT_Y.setSingleStep(0.1)
        self.sbBT_Y.setObjectName(_fromUtf8("sbBT_Y"))
        self.horizontalLayout_4.addWidget(self.sbBT_Y)
        self.gridTop.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbGS = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbGS.sizePolicy().hasHeightForWidth())
        self.rbGS.setSizePolicy(sizePolicy)
        self.rbGS.setMinimumSize(QtCore.QSize(185, 0))
        self.rbGS.setObjectName(_fromUtf8("rbGS"))
        self.horizontalLayout.addWidget(self.rbGS)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.sbGS_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbGS_X.setAccelerated(True)
        self.sbGS_X.setKeyboardTracking(False)
        self.sbGS_X.setDecimals(2)
        self.sbGS_X.setMinimum(-100.0)
        self.sbGS_X.setMaximum(100.0)
        self.sbGS_X.setSingleStep(1.0)
        self.sbGS_X.setObjectName(_fromUtf8("sbGS_X"))
        self.horizontalLayout.addWidget(self.sbGS_X)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sbGS_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbGS_Y.setAccelerated(True)
        self.sbGS_Y.setMinimum(-100.0)
        self.sbGS_Y.setMaximum(100.0)
        self.sbGS_Y.setSingleStep(1.0)
        self.sbGS_Y.setObjectName(_fromUtf8("sbGS_Y"))
        self.horizontalLayout.addWidget(self.sbGS_Y)
        self.gridTop.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.rbIBS = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbIBS.sizePolicy().hasHeightForWidth())
        self.rbIBS.setSizePolicy(sizePolicy)
        self.rbIBS.setMinimumSize(QtCore.QSize(185, 0))
        self.rbIBS.setObjectName(_fromUtf8("rbIBS"))
        self.horizontalLayout_13.addWidget(self.rbIBS)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        self.sbIBS_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIBS_X.setDecimals(4)
        self.sbIBS_X.setMinimum(-1000.0)
        self.sbIBS_X.setMaximum(1000.0)
        self.sbIBS_X.setObjectName(_fromUtf8("sbIBS_X"))
        self.horizontalLayout_13.addWidget(self.sbIBS_X)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.sbIBS_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIBS_Y.setDecimals(4)
        self.sbIBS_Y.setMinimum(-1000.0)
        self.sbIBS_Y.setMaximum(1000.0)
        self.sbIBS_Y.setObjectName(_fromUtf8("sbIBS_Y"))
        self.horizontalLayout_13.addWidget(self.sbIBS_Y)
        self.gridTop.addLayout(self.horizontalLayout_13, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.rbRC = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbRC.sizePolicy().hasHeightForWidth())
        self.rbRC.setSizePolicy(sizePolicy)
        self.rbRC.setMinimumSize(QtCore.QSize(185, 0))
        self.rbRC.setObjectName(_fromUtf8("rbRC"))
        self.horizontalLayout_5.addWidget(self.rbRC)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.sbRC_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbRC_X.setDecimals(4)
        self.sbRC_X.setMinimum(-100.0)
        self.sbRC_X.setMaximum(100.0)
        self.sbRC_X.setSingleStep(0.1)
        self.sbRC_X.setObjectName(_fromUtf8("sbRC_X"))
        self.horizontalLayout_5.addWidget(self.sbRC_X)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.sbRC_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbRC_Y.setDecimals(4)
        self.sbRC_Y.setMinimum(-100.0)
        self.sbRC_Y.setMaximum(100.0)
        self.sbRC_Y.setSingleStep(0.1)
        self.sbRC_Y.setObjectName(_fromUtf8("sbRC_Y"))
        self.horizontalLayout_5.addWidget(self.sbRC_Y)
        self.gridTop.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbIMS = QtGui.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbIMS.sizePolicy().hasHeightForWidth())
        self.rbIMS.setSizePolicy(sizePolicy)
        self.rbIMS.setMinimumSize(QtCore.QSize(185, 0))
        self.rbIMS.setObjectName(_fromUtf8("rbIMS"))
        self.horizontalLayout_6.addWidget(self.rbIMS)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.sbIMS_X = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIMS_X.setDecimals(4)
        self.sbIMS_X.setMinimum(-1000.0)
        self.sbIMS_X.setMaximum(1000.0)
        self.sbIMS_X.setObjectName(_fromUtf8("sbIMS_X"))
        self.horizontalLayout_6.addWidget(self.sbIMS_X)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.sbIMS_Y = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbIMS_Y.setDecimals(4)
        self.sbIMS_Y.setMinimum(-1000.0)
        self.sbIMS_Y.setMaximum(1000.0)
        self.sbIMS_Y.setObjectName(_fromUtf8("sbIMS_Y"))
        self.horizontalLayout_6.addWidget(self.sbIMS_Y)
        self.gridTop.addLayout(self.horizontalLayout_6, 11, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridTop)
        self.gridBottom = QtGui.QGridLayout()
        self.gridBottom.setObjectName(_fromUtf8("gridBottom"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(125, 0))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_11.addWidget(self.label_25)
        self.sbStepY = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStepY.setMinimum(-100.0)
        self.sbStepY.setMaximum(100.0)
        self.sbStepY.setSingleStep(0.1)
        self.sbStepY.setObjectName(_fromUtf8("sbStepY"))
        self.horizontalLayout_11.addWidget(self.sbStepY)
        self.labelYunit = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelYunit.sizePolicy().hasHeightForWidth())
        self.labelYunit.setSizePolicy(sizePolicy)
        self.labelYunit.setObjectName(_fromUtf8("labelYunit"))
        self.horizontalLayout_11.addWidget(self.labelYunit)
        self.gridBottom.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(125, 0))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_10.addWidget(self.label_24)
        self.sbStepX = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStepX.setMinimum(-100.0)
        self.sbStepX.setMaximum(100.0)
        self.sbStepX.setSingleStep(0.1)
        self.sbStepX.setObjectName(_fromUtf8("sbStepX"))
        self.horizontalLayout_10.addWidget(self.sbStepX)
        self.labelXunit = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXunit.sizePolicy().hasHeightForWidth())
        self.labelXunit.setSizePolicy(sizePolicy)
        self.labelXunit.setObjectName(_fromUtf8("labelXunit"))
        self.horizontalLayout_10.addWidget(self.labelXunit)
        self.gridBottom.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(125, 0))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_12.addWidget(self.label_26)
        self.sbStepZ = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sbStepZ.setEnabled(False)
        self.sbStepZ.setMinimum(-100.0)
        self.sbStepZ.setMaximum(100.0)
        self.sbStepZ.setSingleStep(0.1)
        self.sbStepZ.setObjectName(_fromUtf8("sbStepZ"))
        self.horizontalLayout_12.addWidget(self.sbStepZ)
        self.labelZunit = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelZunit.sizePolicy().hasHeightForWidth())
        self.labelZunit.setSizePolicy(sizePolicy)
        self.labelZunit.setObjectName(_fromUtf8("labelZunit"))
        self.horizontalLayout_12.addWidget(self.labelZunit)
        self.gridBottom.addLayout(self.horizontalLayout_12, 6, 0, 1, 1)
        self.SliderY = QwtSlider(self.verticalLayoutWidget)
        self.SliderY.setScalePosition(QwtSlider.TopScale)
        self.SliderY.setBgStyle(QwtSlider.BgSlot)
        self.SliderY.setThumbLength(32)
        self.SliderY.setObjectName(_fromUtf8("SliderY"))
        self.gridBottom.addWidget(self.SliderY, 3, 0, 1, 1)
        self.SliderZ = QwtSlider(self.verticalLayoutWidget)
        self.SliderZ.setScalePosition(QwtSlider.TopScale)
        self.SliderZ.setBgStyle(QwtSlider.BgSlot)
        self.SliderZ.setObjectName(_fromUtf8("SliderZ"))
        self.gridBottom.addWidget(self.SliderZ, 5, 0, 1, 1)
        self.SliderX = QwtSlider(self.verticalLayoutWidget)
        self.SliderX.setScalePosition(QwtSlider.TopScale)
        self.SliderX.setBgStyle(QwtSlider.BgSlot)
        self.SliderX.setObjectName(_fromUtf8("SliderX"))
        self.gridBottom.addWidget(self.SliderX, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridBottom)
        DeflectorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DeflectorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMicroscope = QtGui.QMenu(self.menubar)
        self.menuMicroscope.setObjectName(_fromUtf8("menuMicroscope"))
        DeflectorWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DeflectorWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DeflectorWindow.setStatusBar(self.statusbar)
        self.actionSimulator = QtGui.QAction(DeflectorWindow)
        self.actionSimulator.setCheckable(True)
        self.actionSimulator.setObjectName(_fromUtf8("actionSimulator"))
        self.actionFEI_Titan = QtGui.QAction(DeflectorWindow)
        self.actionFEI_Titan.setCheckable(True)
        self.actionFEI_Titan.setObjectName(_fromUtf8("actionFEI_Titan"))
        self.actionReInit = QtGui.QAction(DeflectorWindow)
        self.actionReInit.setEnabled(False)
        self.actionReInit.setObjectName(_fromUtf8("actionReInit"))
        self.menuMicroscope.addSeparator()
        self.menuMicroscope.addAction(self.actionSimulator)
        self.menuMicroscope.addAction(self.actionFEI_Titan)
        self.menuMicroscope.addSeparator()
        self.menuMicroscope.addAction(self.actionReInit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMicroscope.menuAction())

        self.retranslateUi(DeflectorWindow)
        QtCore.QMetaObject.connectSlotsByName(DeflectorWindow)

    def retranslateUi(self, DeflectorWindow):
        DeflectorWindow.setWindowTitle(_translate("DeflectorWindow", "Persistant Direct Alignments", None))
        self.rbDS.setText(_translate("DeflectorWindow", "Diffraction Shift (mrad)", None))
        self.label_22.setText(_translate("DeflectorWindow", "X", None))
        self.label_23.setText(_translate("DeflectorWindow", "Y", None))
        self.rbBS.setText(_translate("DeflectorWindow", "Beam Shift (nm)", None))
        self.label_6.setText(_translate("DeflectorWindow", "X", None))
        self.label_5.setText(_translate("DeflectorWindow", "Y", None))
        self.rbIBT.setText(_translate("DeflectorWindow", "Image-beam Tilt (mrad)", None))
        self.label_18.setText(_translate("DeflectorWindow", "X", None))
        self.label_19.setText(_translate("DeflectorWindow", "Y", None))
        self.rbGT.setText(_translate("DeflectorWindow", "Gun Tilt (%)", None))
        self.label_4.setText(_translate("DeflectorWindow", "X", None))
        self.label_3.setText(_translate("DeflectorWindow", "Y", None))
        self.label_13.setText(_translate("DeflectorWindow", "Alpha", None))
        self.label_14.setText(_translate("DeflectorWindow", "Beta", None))
        self.label_11.setText(_translate("DeflectorWindow", "Y (nm)", None))
        self.rbStage.setText(_translate("DeflectorWindow", "CompuStage", None))
        self.label_12.setText(_translate("DeflectorWindow", "X (nm)", None))
        self.label_15.setText(_translate("DeflectorWindow", "Z (nm)", None))
        self.rbBT.setText(_translate("DeflectorWindow", "Beam Tilt (mrad)", None))
        self.label_8.setText(_translate("DeflectorWindow", "X", None))
        self.label_7.setText(_translate("DeflectorWindow", "Y", None))
        self.rbGS.setText(_translate("DeflectorWindow", "Gun Shift (%)", None))
        self.label_2.setText(_translate("DeflectorWindow", "X", None))
        self.label.setText(_translate("DeflectorWindow", "Y", None))
        self.rbIBS.setText(_translate("DeflectorWindow", "Image-beam Shift (nm)", None))
        self.label_27.setText(_translate("DeflectorWindow", "X", None))
        self.label_28.setText(_translate("DeflectorWindow", "Y", None))
        self.rbRC.setText(_translate("DeflectorWindow", "Rotation Center (mrad)", None))
        self.label_10.setText(_translate("DeflectorWindow", "X", None))
        self.label_9.setText(_translate("DeflectorWindow", "Y", None))
        self.rbIMS.setText(_translate("DeflectorWindow", "Image Shift (nm)", None))
        self.label_16.setText(_translate("DeflectorWindow", "X", None))
        self.label_17.setText(_translate("DeflectorWindow", "Y", None))
        self.label_25.setText(_translate("DeflectorWindow", "Y-step", None))
        self.labelYunit.setText(_translate("DeflectorWindow", "nm", None))
        self.label_24.setText(_translate("DeflectorWindow", "X-step", None))
        self.labelXunit.setText(_translate("DeflectorWindow", "nm", None))
        self.label_26.setText(_translate("DeflectorWindow", "Z-step", None))
        self.labelZunit.setText(_translate("DeflectorWindow", "nm", None))
        self.menuFile.setTitle(_translate("DeflectorWindow", "File", None))
        self.menuMicroscope.setTitle(_translate("DeflectorWindow", "Microscope", None))
        self.actionSimulator.setText(_translate("DeflectorWindow", "Simulator", None))
        self.actionFEI_Titan.setText(_translate("DeflectorWindow", "FEI Titan", None))
        self.actionReInit.setText(_translate("DeflectorWindow", "Re-init", None))

from qwt_slider import QwtSlider
